/**
 * Scenario presets and character narratives for the visualizer.
 * All scenarios run for 730 days (2 years).
 */

const T = 730; // 2 years

// ============================================================
// PHENOMENA SCENARIOS (mechanistic demonstrations)
// ============================================================
const SCENARIOS = {
  bootstrap: {
    name: "Successful Bootstrapping",
    description: "Low complexity (walking 15min/day). H grows steadily over months.",
    phenomena: ["P1", "P3", "P30"],
    category: "scenario",
    params: { C: 0.2, alpha_H: 0.045, beta_M: 0.12, gamma: 0.3, sigma_noise: 0.015 },
    initial: { H: 0.02, M: 1.2, E: 0.3, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.5, label: 'Decided to start walking' },
      { time: 180, type: 'social', amplitude: 0.8, label: 'Walking buddy joined' },
      { time: 365, type: 'escalate', amplitude: 0.6, label: 'Added light jogging' },
      { time: 500, type: 'stress', amplitude: 0.5, label: 'Work crunch' },
    ],
    t_end: T,
  },

  false_hope: {
    name: "False Hope Limit Cycle",
    description: "Intense gym resolution. Periodic re-motivation without lasting H growth over 2 years.",
    phenomena: ["P11", "P33", "P7"],
    category: "scenario",
    params: { C: 0.8, alpha_H: 0.045, phi_S: 1.5, kappa: 0.35, E_crit: -1.0,
              beta_M: 0.2, lambda: 0.35, gamma: 0.15 },
    initial: { H: 0.02, M: 0.3, E: 0, I: 0 },
    events: [
      { time: 0, type: 'new_year', amplitude: 2.0, label: "Year 1 New Year's Resolution" },
      { time: 45, type: 'lapse', amplitude: 1.0, label: 'Missed two weeks' },
      { time: 90, type: 'shock', amplitude: 1.0, label: 'Spring recommitment' },
      { time: 150, type: 'lapse', amplitude: 1.2, label: 'Summer vacation derailed' },
      { time: 200, type: 'shock', amplitude: 0.8, label: 'Saw old photos' },
      { time: 270, type: 'stress', amplitude: 0.6, label: 'Holiday stress' },
      { time: 365, type: 'new_year', amplitude: 1.8, label: "Year 2 New Year's Resolution" },
      { time: 420, type: 'lapse', amplitude: 1.0, label: 'Pattern repeating' },
      { time: 500, type: 'shock', amplitude: 0.8, label: 'Friend lost weight' },
      { time: 600, type: 'simplify', amplitude: 2.0, label: 'Finally tried just walking' },
      { time: 650, type: 'social', amplitude: 0.5, label: 'Walking group' },
    ],
    t_end: T,
  },

  indulgence: {
    name: "Indulgence Trap",
    description: "Watches fitness content, fantasizes about results. M leaks through phantom reward.",
    phenomena: ["P17", "P31"],
    category: "scenario",
    params: { C: 0.7, alpha_H: 0.045, f_0: 0.6, gamma_ind: 0.2, phi_ind: 0.1,
              gamma: 0.12, beta_M: 0.1, sigma_noise: 0.01 },
    initial: { H: 0.02, M: 0.8, E: 0.5, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.5, label: 'Inspired by fitness influencer' },
      { time: 120, type: 'shock', amplitude: 0.3, label: 'Another inspiring video' },
      { time: 250, type: 'shock', amplitude: 0.4, label: 'Bought workout program' },
      { time: 400, type: 'simplify', amplitude: 1.5, label: 'Realized watching isnt doing' },
      { time: 400, type: 'impl_intention', amplitude: 0.8, label: 'Set alarm for morning walk' },
    ],
    t_end: T,
  },

  complexity_overshoot: {
    name: "Complexity Overshoot -> Simplify -> Success",
    description: "All-in on CrossFit fails. Simplifies to walking. Eventually builds back up.",
    phenomena: ["P32", "P9"],
    category: "scenario",
    params: { C: 0.95, alpha_H: 0.045, lambda: 0.5, beta_M: 0.2, gamma: 0.1, sigma_noise: 0.015 },
    initial: { H: 0.02, M: 1.5, E: 1.5, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 1.0, label: 'All-in CrossFit commitment' },
      { time: 30, type: 'lapse', amplitude: 1.5, label: 'Burned out after 4 weeks' },
      { time: 90, type: 'simplify', amplitude: 2.5, label: 'Friend: just walk 15min/day' },
      { time: 200, type: 'social', amplitude: 0.8, label: 'Walking buddy' },
      { time: 350, type: 'escalate', amplitude: 0.5, label: 'Added gym once a week' },
      { time: 500, type: 'escalate', amplitude: 0.5, label: 'Gym twice a week now' },
    ],
    t_end: T,
  },

  what_the_hell: {
    name: "What-the-Hell Effect",
    description: "Strict diet broken by birthday cake. Catastrophic M collapse. Recovery attempt later.",
    phenomena: ["P12", "P14"],
    category: "scenario",
    params: { C: 0.7, alpha_H: 0.045, kappa_wth: 1.5, E_wth: 1.0,
              beta_M: 0.15, lambda: 0.3, sigma_noise: 0.01 },
    initial: { H: 0.05, M: 0.8, E: 0.6, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 1.0, label: 'Started strict diet' },
      { time: 21, type: 'lapse', amplitude: 1.5, label: 'Birthday party (lapse)' },
      { time: 120, type: 'simplify', amplitude: 2.0, label: 'Therapist: stop the all-or-nothing' },
      { time: 120, type: 'shock', amplitude: 0.8, label: 'New flexible approach' },
      { time: 300, type: 'social', amplitude: 0.5, label: 'Cooking class with friend' },
      { time: 450, type: 'stress', amplitude: 0.6, label: 'Work deadline' },
    ],
    t_end: T,
  },

  identity_stable: {
    name: "Identity-Stabilized Maintenance",
    description: "Veteran runner survives injury + stress over 2 years thanks to identity.",
    phenomena: ["P21", "P23", "P20"],
    category: "scenario",
    params: { C: 0.4, alpha_H: 0.045, sigma_noise: 0.02 },
    initial: { H: 0.85, M: 0.6, E: 0, I: 0.8 },
    events: [
      { time: 60, type: 'injury_start', amplitude: 1.0, label: 'Knee injury' },
      { time: 120, type: 'injury_end', amplitude: 1.0, label: 'Cleared for light activity' },
      { time: 200, type: 'stress', amplitude: 0.7, label: 'Work crisis' },
      { time: 350, type: 'context_disruption', amplitude: 0.4, label: 'Schedule change' },
      { time: 500, type: 'injury_start', amplitude: 1.0, label: 'Back strain' },
      { time: 530, type: 'injury_end', amplitude: 1.0, label: 'Healed' },
      { time: 600, type: 'stress', amplitude: 0.5, label: 'Family issue' },
    ],
    t_end: T,
  },

  context_disruption: {
    name: "Context Disruption & Recovery",
    description: "Established habit disrupted by city move. Identity-aided recovery.",
    phenomena: ["P4", "P21", "P34"],
    category: "scenario",
    params: { C: 0.4, alpha_H: 0.045, sigma_noise: 0.015 },
    initial: { H: 0.7, M: 0.8, E: 0, I: 0.5 },
    events: [
      { time: 60, type: 'context_disruption', amplitude: 0.6, label: 'Moved to new city' },
      { time: 90, type: 'shock', amplitude: 0.5, label: 'Found new gym' },
      { time: 120, type: 'social', amplitude: 0.8, label: 'Joined running group' },
      { time: 300, type: 'stress', amplitude: 0.4, label: 'Adjusting to new job' },
      { time: 450, type: 'escalate', amplitude: 0.5, label: 'Signed up for local 10K' },
    ],
    t_end: T,
  },

  stress_relapse: {
    name: "Stress-Induced Relapse",
    description: "Early habit former hit by job loss. Recovers months later with social support.",
    phenomena: ["P23", "P35"],
    category: "scenario",
    params: { C: 0.6, alpha_H: 0.045, beta_M: 0.2, lambda: 0.3, sigma_noise: 0.02 },
    initial: { H: 0.05, M: 0.7, E: 0.3, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.6, label: 'Started exercising' },
      { time: 45, type: 'stress', amplitude: 0.9, label: 'Job loss' },
      { time: 150, type: 'shock', amplitude: 0.5, label: 'New job, fresh start' },
      { time: 150, type: 'simplify', amplitude: 1.0, label: 'Just lunchtime walks now' },
      { time: 250, type: 'social', amplitude: 0.8, label: 'Coworker walks with you' },
      { time: 400, type: 'escalate', amplitude: 0.5, label: 'Added evening gym' },
      { time: 550, type: 'stress', amplitude: 0.5, label: 'Project deadline' },
    ],
    t_end: T,
  },
};

// ============================================================
// CHARACTER NARRATIVES (from calibration backstories)
// ============================================================
const CHARACTERS = {
  sarah_grad: {
    name: "Sarah (23, Grad Student)",
    description: "PhD student, anxiety-driven. Never athletic. Therapist suggested running.",
    category: "character",
    params: { C: 0.3, alpha_H: 0.045, beta_M: 0.12, sigma_noise: 0.02 },
    initial: { H: 0.02, M: 0.6, E: 0.3, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.8, label: 'Therapist recommends exercise' },
      { time: 30, type: 'stress', amplitude: 0.6, label: 'Qualifying exam prep' },
      { time: 60, type: 'lapse', amplitude: 0.5, label: 'Skipped a week during exams' },
      { time: 90, type: 'social', amplitude: 0.5, label: 'Labmate starts joining her walks' },
      { time: 150, type: 'stress', amplitude: 0.4, label: 'Paper deadline' },
      { time: 210, type: 'context_disruption', amplitude: 0.3, label: 'Summer schedule change' },
      { time: 250, type: 'shock', amplitude: 0.3, label: 'Noticed anxiety improving' },
      { time: 365, type: 'stress', amplitude: 0.7, label: 'Committee meeting crisis' },
      { time: 400, type: 'social', amplitude: 0.5, label: 'Running club on campus' },
      { time: 500, type: 'escalate', amplitude: 0.3, label: 'Started Couch to 5K' },
      { time: 600, type: 'stress', amplitude: 0.5, label: 'Dissertation writing crunch' },
      { time: 650, type: 'shock', amplitude: 0.5, label: 'Ran first 5K!' },
    ],
    t_end: T,
  },

  marcus_tech: {
    name: "Marcus (26, Startup Engineer)",
    description: "Ex-lifter, 60hr weeks. Wedding photos shocked him. Knows gym but zero habit.",
    category: "character",
    params: { C: 0.7, alpha_H: 0.045, beta_M: 0.18, lambda: 0.3, sigma_noise: 0.02 },
    initial: { H: 0.05, M: 1.2, E: 0.8, I: 0.1 },
    events: [
      { time: 0, type: 'shock', amplitude: 1.5, label: 'Wedding photos -- "what happened to me"' },
      { time: 20, type: 'stress', amplitude: 0.7, label: 'Product launch crunch' },
      { time: 40, type: 'lapse', amplitude: 1.0, label: 'Havent been to gym in 2 weeks' },
      { time: 90, type: 'simplify', amplitude: 2.0, label: 'College buddy: just come walk at lunch' },
      { time: 90, type: 'social', amplitude: 0.8, label: 'Lunch walk buddy' },
      { time: 180, type: 'stress', amplitude: 0.5, label: 'Sprint deadline' },
      { time: 220, type: 'escalate', amplitude: 0.5, label: 'Added gym after work 2x/week' },
      { time: 300, type: 'stress', amplitude: 0.8, label: 'Startup funding crisis' },
      { time: 350, type: 'lapse', amplitude: 0.7, label: 'Missed gym for a month' },
      { time: 400, type: 'shock', amplitude: 0.5, label: 'Buddy says he missed him at gym' },
      { time: 500, type: 'escalate', amplitude: 0.5, label: 'Back to 3x/week lifting' },
      { time: 600, type: 'stress', amplitude: 0.4, label: 'Normal work stress' },
      { time: 650, type: 'social', amplitude: 0.5, label: 'Gym crew formed' },
    ],
    t_end: T,
  },

  mei_exec: {
    name: "Mei (38, VP Operations)",
    description: "High-powered exec, 30% travel. Personal trainer when in town. Half marathon goal.",
    category: "character",
    params: { C: 0.8, alpha_H: 0.045, beta_M: 0.2, lambda: 0.35, sigma_noise: 0.02 },
    initial: { H: 0.15, M: 1.5, E: 1.0, I: 0.1 },
    events: [
      { time: 0, type: 'shock', amplitude: 1.5, label: 'Signed up for half marathon' },
      { time: 14, type: 'context_disruption', amplitude: 0.3, label: 'Week-long business trip' },
      { time: 30, type: 'context_disruption', amplitude: 0.3, label: 'Another trip' },
      { time: 50, type: 'stress', amplitude: 0.7, label: 'Board presentation' },
      { time: 60, type: 'context_disruption', amplitude: 0.3, label: 'Conference travel' },
      { time: 90, type: 'lapse', amplitude: 1.2, label: 'Training plan totally derailed' },
      { time: 120, type: 'simplify', amplitude: 2.5, label: 'Trainer: forget the race, just move when you can' },
      { time: 150, type: 'impl_intention', amplitude: 0.8, label: 'Hotel gym rule: 20min every trip' },
      { time: 200, type: 'context_disruption', amplitude: 0.3, label: 'Trip to Asia' },
      { time: 250, type: 'social', amplitude: 0.5, label: 'Found a travel running app group' },
      { time: 365, type: 'shock', amplitude: 0.5, label: 'Year review: actually exercised 3x/week avg' },
      { time: 400, type: 'escalate', amplitude: 0.5, label: 'Maybe that half marathon again...' },
      { time: 450, type: 'context_disruption', amplitude: 0.3, label: 'Travel season' },
      { time: 550, type: 'stress', amplitude: 0.6, label: 'Reorg at company' },
      { time: 650, type: 'shock', amplitude: 0.8, label: 'Ran the half marathon!' },
    ],
    t_end: T,
  },

  carlos_runner: {
    name: "Carlos (42, Teacher/Coach)",
    description: "Former competitive runner. Coaches HS track. Knee problems. Strong identity.",
    category: "character",
    params: { C: 0.5, alpha_H: 0.045, sigma_noise: 0.02 },
    initial: { H: 0.65, M: 0.4, E: -0.2, I: 0.7 },
    events: [
      { time: 30, type: 'injury_start', amplitude: 1.0, label: 'Knee flare-up, doctor says rest' },
      { time: 75, type: 'injury_end', amplitude: 1.0, label: 'Cleared for light jogging' },
      { time: 75, type: 'simplify', amplitude: 1.0, label: 'Walk/jog only, no speed work' },
      { time: 120, type: 'stress', amplitude: 0.4, label: 'Track season coaching demands' },
      { time: 200, type: 'escalate', amplitude: 0.3, label: 'Started easy tempo runs again' },
      { time: 280, type: 'injury_start', amplitude: 1.0, label: 'Knee again -- worse this time' },
      { time: 350, type: 'injury_end', amplitude: 1.0, label: 'PT says swimming + cycling OK' },
      { time: 350, type: 'simplify', amplitude: 1.5, label: 'Shifted to cross-training' },
      { time: 400, type: 'shock', amplitude: 0.5, label: 'Student says "coach you inspired me"' },
      { time: 500, type: 'social', amplitude: 0.5, label: 'Joined masters swim group' },
      { time: 600, type: 'escalate', amplitude: 0.3, label: 'Light running again' },
      { time: 680, type: 'stress', amplitude: 0.3, label: 'End of school year' },
    ],
    t_end: T,
  },

  aisha_nurse: {
    name: "Aisha (33, ICU Nurse)",
    description: "Night shift 12hrs. Circadian destroyed. Knows exercise would help. Schedule is the enemy.",
    category: "character",
    params: { C: 0.3, alpha_H: 0.045, beta_M: 0.2, sigma_noise: 0.02 },
    initial: { H: 0.02, M: 0.5, E: 0.2, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.5, label: 'New Years: this year I exercise' },
      { time: 14, type: 'stress', amplitude: 0.7, label: 'COVID surge, extra shifts' },
      { time: 45, type: 'stress', amplitude: 0.5, label: 'Exhaustion from double shifts' },
      { time: 90, type: 'simplify', amplitude: 1.0, label: 'Just 10min yoga on days off' },
      { time: 120, type: 'stress', amplitude: 0.6, label: 'Difficult patient outcomes' },
      { time: 180, type: 'context_disruption', amplitude: 0.3, label: 'Shift rotation changed' },
      { time: 220, type: 'social', amplitude: 0.5, label: 'Nurse colleague walks on break' },
      { time: 300, type: 'stress', amplitude: 0.8, label: 'Burnout episode' },
      { time: 350, type: 'shock', amplitude: 0.5, label: 'Noticed sleep improved on walk days' },
      { time: 400, type: 'impl_intention', amplitude: 0.8, label: 'Walk immediately after shift ends' },
      { time: 500, type: 'stress', amplitude: 0.5, label: 'Staffing shortage' },
      { time: 550, type: 'social', amplitude: 0.5, label: 'Wellness program at hospital' },
      { time: 650, type: 'stress', amplitude: 0.4, label: 'Holiday coverage' },
    ],
    t_end: T,
  },

  sam_freshman: {
    name: "Sam (19, College Freshman)",
    description: "Skinny, watched too many fitness YouTubers. 6-day PPL split from Reddit. Zero patience.",
    category: "character",
    params: { C: 0.9, alpha_H: 0.045, beta_M: 0.2, sigma_noise: 0.02 },
    initial: { H: 0.02, M: 2.0, E: 2.0, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 2.0, label: 'Move-in day: finally have a gym!' },
      { time: 7, type: 'escalate', amplitude: 0.5, label: 'Bought creatine and pre-workout' },
      { time: 21, type: 'lapse', amplitude: 1.0, label: 'Midterms killed gym schedule' },
      { time: 35, type: 'lapse', amplitude: 1.5, label: 'Havent gone in 2 weeks, feels pointless' },
      { time: 90, type: 'shock', amplitude: 0.8, label: 'Saw a transformation post, fired up again' },
      { time: 100, type: 'lapse', amplitude: 1.0, label: 'Same pattern, dropped off again' },
      { time: 150, type: 'context_disruption', amplitude: 0.5, label: 'Semester break, no campus gym' },
      { time: 180, type: 'social', amplitude: 0.8, label: 'Roommate says "lets just go 3x/week"' },
      { time: 180, type: 'simplify', amplitude: 3.0, label: 'Ditched PPL for full-body 3x/week' },
      { time: 250, type: 'stress', amplitude: 0.5, label: 'Harder sophomore classes' },
      { time: 350, type: 'escalate', amplitude: 0.3, label: 'Added a 4th day' },
      { time: 400, type: 'social', amplitude: 0.5, label: 'Regular gym crew now' },
      { time: 500, type: 'shock', amplitude: 0.5, label: 'Friend said "you look bigger"' },
      { time: 550, type: 'context_disruption', amplitude: 0.3, label: 'Summer break' },
      { time: 600, type: 'shock', amplitude: 0.3, label: 'Back at school, back at gym' },
    ],
    t_end: T,
  },

  derek_yoyo: {
    name: "Derek (45, Sales Director)",
    description: "5th weight loss attempt. 265lbs. Knows every diet. Cynical but desperate.",
    category: "character",
    params: { C: 0.6, alpha_H: 0.045, beta_M: 0.18, kappa: 0.35, sigma_noise: 0.02 },
    initial: { H: 0.03, M: 0.5, E: -0.5, I: 0 },
    events: [
      { time: 0, type: 'new_year', amplitude: 1.5, label: 'Another January, another attempt' },
      { time: 21, type: 'lapse', amplitude: 1.0, label: 'Client dinner, ate everything' },
      { time: 45, type: 'lapse', amplitude: 1.5, label: 'Weighed in, gained 2lbs. Why bother?' },
      { time: 120, type: 'shock', amplitude: 0.8, label: 'Doctor: pre-diabetic now' },
      { time: 150, type: 'simplify', amplitude: 2.0, label: 'Doctor: just walk 20min after dinner' },
      { time: 200, type: 'stress', amplitude: 0.6, label: 'Q3 sales targets' },
      { time: 250, type: 'shock', amplitude: 0.3, label: 'A1C improved slightly' },
      { time: 300, type: 'stress', amplitude: 0.7, label: 'Travel season' },
      { time: 350, type: 'lapse', amplitude: 0.7, label: 'Fell off during travel' },
      { time: 380, type: 'social', amplitude: 0.5, label: 'Wife started walking with him' },
      { time: 450, type: 'shock', amplitude: 0.5, label: 'Down 8lbs -- first time in years' },
      { time: 500, type: 'stress', amplitude: 0.5, label: 'End of year push' },
      { time: 550, type: 'escalate', amplitude: 0.3, label: 'Added Saturday morning yoga' },
      { time: 650, type: 'shock', amplitude: 0.8, label: 'Doctor: no longer pre-diabetic!' },
    ],
    t_end: T,
  },

  helen_retired: {
    name: "Helen (62, Retired Teacher)",
    description: "Widowed, determined not to decline like her mother. Silver Sneakers class. Plenty of time.",
    category: "character",
    params: { C: 0.3, alpha_H: 0.045, beta_M: 0.1, sigma_noise: 0.015 },
    initial: { H: 0.02, M: 0.8, E: 0.2, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 0.8, label: 'Watched mother struggle with stairs' },
      { time: 7, type: 'social', amplitude: 1.2, label: 'Joined Silver Sneakers at community center' },
      { time: 60, type: 'injury_start', amplitude: 1.0, label: 'Turned ankle in class' },
      { time: 80, type: 'injury_end', amplitude: 1.0, label: 'Cleared to return' },
      { time: 120, type: 'social', amplitude: 0.5, label: 'Made friends in class, they text her' },
      { time: 200, type: 'stress', amplitude: 0.3, label: 'Granddaughter visiting (good stress)' },
      { time: 300, type: 'escalate', amplitude: 0.3, label: 'Added water aerobics' },
      { time: 365, type: 'shock', amplitude: 0.5, label: 'Doctor amazed at balance test improvement' },
      { time: 450, type: 'injury_start', amplitude: 1.0, label: 'Hip bothering her' },
      { time: 480, type: 'injury_end', amplitude: 1.0, label: 'PT helped, modified exercises' },
      { time: 480, type: 'simplify', amplitude: 0.5, label: 'Chair exercises on bad days' },
      { time: 550, type: 'social', amplitude: 0.5, label: 'Became the one who texts others' },
      { time: 650, type: 'shock', amplitude: 0.3, label: 'Carried groceries up stairs easily' },
    ],
    t_end: T,
  },

  lisa_divorce: {
    name: "Lisa (37, Post-Divorce)",
    description: "Using fitness to reclaim identity. CrossFit intro. Community matters as much as exercise.",
    category: "character",
    params: { C: 0.7, alpha_H: 0.045, beta_M: 0.18, sigma_noise: 0.02 },
    initial: { H: 0.02, M: 1.8, E: 1.2, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 2.0, label: 'Signed up for CrossFit intro' },
      { time: 7, type: 'social', amplitude: 1.0, label: 'CrossFit community welcomed her' },
      { time: 30, type: 'stress', amplitude: 0.8, label: 'Custody schedule conflict' },
      { time: 45, type: 'injury_start', amplitude: 1.0, label: 'Shoulder strain from bad form' },
      { time: 60, type: 'injury_end', amplitude: 1.0, label: 'Modified movements OK' },
      { time: 60, type: 'simplify', amplitude: 1.5, label: 'Coach: scale everything, just show up' },
      { time: 120, type: 'stress', amplitude: 0.7, label: 'Ex making custody difficult' },
      { time: 180, type: 'social', amplitude: 0.5, label: 'CrossFit friend babysits sometimes' },
      { time: 250, type: 'stress', amplitude: 0.5, label: 'Kids struggling at school' },
      { time: 300, type: 'shock', amplitude: 0.5, label: 'Did first unassisted pullup!' },
      { time: 365, type: 'stress', amplitude: 0.6, label: 'Anniversay of divorce, emotional' },
      { time: 400, type: 'escalate', amplitude: 0.3, label: 'Signed up for local competition' },
      { time: 500, type: 'stress', amplitude: 0.4, label: 'Work promotion (good stress)' },
      { time: 600, type: 'social', amplitude: 0.5, label: 'Became a regular, people know her name' },
      { time: 680, type: 'shock', amplitude: 0.5, label: 'Kids said "mom youre so strong"' },
    ],
    t_end: T,
  },

  alex_adhd: {
    name: "Alex (30, ADHD Freelancer)",
    description: "8 failed exercise programs. Hyperfocuses then drops. Knows the pattern, can't break it.",
    category: "character",
    params: { C: 0.5, alpha_H: 0.045, beta_M: 0.2, sigma_noise: 0.025 },
    initial: { H: 0.05, M: 1.6, E: 0.9, I: 0 },
    events: [
      { time: 0, type: 'shock', amplitude: 1.5, label: 'Hyperfocus: new boxing gym!' },
      { time: 21, type: 'lapse', amplitude: 1.0, label: 'Novelty wore off. Stopped going.' },
      { time: 60, type: 'shock', amplitude: 1.2, label: 'Hyperfocus: bought a bike!' },
      { time: 80, type: 'lapse', amplitude: 0.8, label: 'Bike collecting dust after 3 weeks' },
      { time: 150, type: 'shock', amplitude: 0.8, label: 'Read about exercise for ADHD' },
      { time: 150, type: 'simplify', amplitude: 2.0, label: 'Decided: just 10min walk when stuck' },
      { time: 150, type: 'impl_intention', amplitude: 1.0, label: 'When code wont compile, walk around block' },
      { time: 200, type: 'stress', amplitude: 0.5, label: 'Client deadline, hyperfocus on work' },
      { time: 250, type: 'shock', amplitude: 0.3, label: 'Noticed walks help him think' },
      { time: 350, type: 'escalate', amplitude: 0.3, label: 'Walks got longer naturally' },
      { time: 400, type: 'stress', amplitude: 0.6, label: 'Freelance income gap' },
      { time: 450, type: 'social', amplitude: 0.5, label: 'Found ADHD exercise accountability group' },
      { time: 550, type: 'shock', amplitude: 1.0, label: 'Hyperfocus: trail running!' },
      { time: 570, type: 'lapse', amplitude: 0.5, label: 'Trail running fad faded' },
      { time: 580, type: 'shock', amplitude: 0.3, label: 'But still walking every day' },
      { time: 650, type: 'escalate', amplitude: 0.3, label: 'Added gym once a week' },
    ],
    t_end: T,
  },
};

// Merge for unified access
const CLUSTER_PRESETS = {}; // Removed old cluster presets, characters replace them

window.SCENARIOS = SCENARIOS;
window.CHARACTERS = CHARACTERS;
window.CLUSTER_PRESETS = CLUSTER_PRESETS;
